# Generated by Django 5.1.2 on 2024-10-23 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventos_usario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='usario',
            new_name='usuario',
        ),
    ]
